### ISSUE TITLE
use process.stdin.setEncoding('utf8')

### ISSUE THREAD

**Issue by dominictarr** [jamen/pull-stdio#1]
a better way to do this:
https://github.com/jamen/pull-stdio/blob/master/index.js#L23-L28

is just to use the setEncoding method on stdin, as in this example,
https://nodejs.org/dist/latest-v6.x/docs/api/process.html#process_process_stdin

then it will have consistent behavior with node core, and you don't need the map,
(also, it should be faster, since it will read directly to a string in c land, instead of to a buffer then copying to string...

**Comment by jamen** [comment]
Switched it to this.  Thanks  :)
